import '../scss/mainContent.scss'

function MainContent({ leftWidth, naviWidth }) {

  return (
    <div className='main-content' style={{ marginLeft: (leftWidth) + (naviWidth)}}>
      <p>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eleifend, turpis non gravida commodo, mi magna iaculis justo, vel eleifend sapien lacus non ligula. Ut ullamcorper scelerisque erat ac scelerisque. Sed nisi nisl, ultrices id massa ut, molestie feugiat nisl. Nam venenatis enim vitae tortor congue, at convallis enim posuere. Quisque interdum vel sapien eget tincidunt. Nunc tempor, sapien ut molestie pretium, metus urna eleifend justo, nec viverra dui nisl id dolor. Nulla sed ex sapien. Etiam non nunc sed nunc consectetur tincidunt quis sed odio. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam finibus rhoncus nibh id aliquam. Cras mi turpis, bibendum sit amet elit sit amet, eleifend mollis leo. Donec pretium ex non bibendum lobortis. Curabitur in risus quis quam porttitor sagittis eget vitae nisi. Nam in felis mollis, rutrum leo sed, hendrerit orci.

Integer ac vestibulum est, eu tincidunt orci. Ut vehicula dui et risus rutrum hendrerit. Ut feugiat massa vel libero consectetur faucibus. In dictum porta aliquet. Mauris sollicitudin ligula sapien, ac placerat felis congue a. Etiam rutrum sit amet purus id vestibulum. Nunc laoreet nisi ac placerat vehicula. Donec consequat tristique mauris vel laoreet. Aenean suscipit dolor sed dapibus aliquam. Nam laoreet dolor libero, vel finibus lacus mattis et. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus.

Proin ut varius lorem, at ullamcorper urna. Etiam laoreet, nisl sit amet finibus ultrices, nisl ex finibus nisi, vitae luctus tortor eros non purus. Duis eu metus luctus, rhoncus metus aliquet, commodo justo. Aenean eget arcu nec quam euismod viverra sed et nulla. Pellentesque quis turpis a nisl efficitur interdum. Phasellus sed dapibus libero. Quisque commodo maximus ex a vulputate.

Ut varius velit non gravida gravida. Etiam varius, nibh eu vehicula finibus, dui enim tempor turpis, vehicula ornare libero massa ac odio. Praesent blandit nulla ac enim feugiat accumsan. Nam lacus nisi, aliquet in nunc eu, rutrum eleifend sapien. Pellentesque sit amet magna pretium velit ullamcorper viverra ut tempus elit. Praesent vel posuere tortor, vitae sagittis sapien. Aenean egestas venenatis orci, blandit accumsan metus blandit ut. Vestibulum tempus sollicitudin quam, id malesuada eros hendrerit sit amet. Suspendisse potenti. Nullam tincidunt finibus consequat. Mauris egestas magna ac rhoncus pharetra. Phasellus aliquam tempus lectus tristique rutrum. Aenean tincidunt laoreet justo, quis consectetur dui eleifend a. Nunc dapibus dui sit amet nulla pretium, nec pellentesque libero tincidunt.

Suspendisse lacus nisi, hendrerit vel dapibus at, finibus eget metus. Ut tincidunt est quis risus facilisis ultrices. Sed id orci ac tortor porta euismod. Pellentesque pellentesque interdum nunc. Sed a sem egestas, vehicula nisi nec, feugiat augue. Nulla lobortis sapien faucibus turpis consequat dictum. Morbi vitae lectus euismod est sollicitudin vulputate. Aenean iaculis sem libero, vitae consectetur libero placerat in. Nam et risus vel lorem convallis interdum. Aenean ut consequat neque.

Integer bibendum interdum rutrum. Sed suscipit aliquam velit. Cras accumsan turpis nunc, et aliquet sem malesuada vitae. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Sed non purus sagittis, dictum enim non, finibus nisl. Nunc vehicula malesuada leo, vitae ornare turpis congue sit amet. Etiam et ex sit amet metus egestas volutpat. Donec venenatis finibus elit, ac accumsan enim lobortis eget. Vestibulum tellus neque, lacinia vel tempus nec, ultrices nec turpis. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi consequat tincidunt dolor, non aliquam massa lacinia vel. Fusce accumsan a risus a congue. Sed non erat elit. Sed tristique neque sed metus sollicitudin accumsan. Vivamus varius nunc ut dignissim volutpat.

Nullam sed neque blandit, placerat ex ac, ullamcorper nibh. Pellentesque id nunc non felis dictum pharetra pellentesque vitae risus. Vivamus imperdiet tortor at velit fringilla, sed varius eros imperdiet. Ut dolor ligula, cursus nec congue quis, euismod id libero. Cras risus sem, auctor sit amet ex sit amet, porta scelerisque velit. Maecenas rutrum turpis in tellus rutrum, in bibendum nisl fermentum. Integer ornare enim sed pellentesque consequat. Nullam rhoncus, eros nec dapibus mollis, mi libero tempus est, id feugiat justo arcu ut risus. Phasellus luctus ultricies bibendum. Fusce felis purus, bibendum id magna in, faucibus venenatis tortor.

Maecenas ornare pharetra nisl, eget dictum mi tristique a. Morbi eget justo enim. Integer luctus nibh neque, sed ornare nunc posuere et. Proin egestas sem ac varius vehicula. Vestibulum tortor lacus, sagittis sit amet consequat vel, efficitur hendrerit nisi. Aenean sed semper sem, id consectetur arcu. Mauris non volutpat est. Pellentesque vitae enim nec ex sodales efficitur at sed lacus. In luctus massa ipsum, vitae accumsan mauris tincidunt at. Nam rutrum erat sed aliquet aliquet. Pellentesque id nisi at ligula lobortis ultricies ac a odio. Cras vitae condimentum urna. Quisque neque magna, euismod dignissim posuere eu, faucibus vitae eros. Pellentesque sed nibh pellentesque, ullamcorper dui bibendum, lacinia leo.

Donec eleifend mauris eu tristique vulputate. In laoreet tellus et dui mattis, vel venenatis lectus consequat. Etiam facilisis cursus enim, at sodales ante euismod et. Donec felis risus, consectetur in magna in, volutpat eleifend nisl. Donec ultrices vulputate laoreet. Proin tempus ullamcorper urna, id rhoncus diam sagittis eu. Curabitur luctus, tortor quis pulvinar facilisis, turpis neque imperdiet augue, mollis malesuada leo nisl eu tellus. Ut rhoncus, lectus sit amet euismod aliquet, sapien metus pharetra nulla, eu ultricies turpis odio nec felis. Maecenas gravida lacinia purus. Quisque nec erat in dui aliquam fermentum. Aenean aliquet consequat tincidunt. Phasellus convallis ipsum et sollicitudin vestibulum. Integer posuere eros non purus imperdiet porttitor. In sit amet ipsum blandit tortor semper consequat. Vivamus ornare ante vel tincidunt imperdiet.

Vestibulum ex enim, auctor a purus sed, pellentesque feugiat justo. Nam viverra porttitor lectus, eget egestas nibh cursus ac. Donec fringilla magna mollis massa placerat fringilla. Curabitur vehicula urna at justo commodo, in aliquam libero feugiat. In velit nisi, consequat eget porttitor vitae, mollis sollicitudin metus. Donec sodales blandit ligula, in scelerisque mi. Aenean tincidunt arcu vel bibendum mattis. Praesent laoreet porta ultrices.

Quisque ut ipsum convallis, convallis purus vel, tristique arcu. Duis eget risus eleifend, rhoncus metus nec, venenatis arcu. Etiam vel maximus odio. Suspendisse id leo ex. Phasellus vestibulum dolor vitae neque ultricies, eu bibendum erat tincidunt. Proin sit amet mauris nulla. Cras aliquet mi augue, vitae congue metus ullamcorper quis. Praesent sit amet quam mi. Nunc sed lectus facilisis, egestas magna quis, tincidunt enim. Vivamus ultricies nisi magna, in tincidunt purus vehicula ac. Pellentesque interdum sed ex at finibus. Nullam ultrices quis ligula non accumsan.

Mauris eu efficitur libero. Phasellus libero velit, finibus non sem eu, pharetra sodales risus. Nam quis neque vel purus malesuada tempor. Cras ultrices efficitur consectetur. Nam scelerisque aliquet rhoncus. Sed eget rhoncus mi. Pellentesque ut suscipit orci, in sollicitudin sem. Etiam non varius nibh. Mauris eu pulvinar felis. Pellentesque tempor erat in dolor interdum, vitae tincidunt mi pulvinar. Pellentesque varius imperdiet lorem, in ullamcorper sapien dictum sit amet. Integer tristique ultrices arcu, et ornare nisi commodo id. Nulla eget justo eros. Quisque quis lobortis quam, ac suscipit tellus. Vestibulum vitae cursus justo.

Nam eget volutpat diam, consequat euismod diam. Aliquam posuere urna faucibus ex tempor laoreet. Proin consequat pharetra sem, eget auctor neque lobortis at. Duis nisi augue, eleifend sodales nisi ut, sollicitudin congue nibh. Pellentesque at elit sem. Aenean ultricies fringilla tellus ac laoreet. Suspendisse suscipit elit risus. Curabitur vitae ante in nibh fermentum sollicitudin. Donec imperdiet nec orci sed laoreet. Etiam et scelerisque arcu, egestas aliquet purus. Morbi eget risus eros. Vivamus non aliquam tortor. Aenean dictum metus urna, sed blandit enim imperdiet in. Nam ac ex sed lectus congue malesuada. In ac massa enim. Morbi sodales cursus justo sit amet gravida.

Praesent congue varius turpis, id convallis arcu interdum a. Duis sem libero, aliquam in mattis eu, tincidunt at est. Ut feugiat sem quis sapien semper cursus. Mauris vitae justo ex. Integer eget pulvinar arcu, posuere luctus ligula. Mauris eget ultricies nisl. Nunc id sapien sed sapien blandit cursus. Nam convallis mi urna, eu sodales neque vestibulum nec. Cras sit amet lacinia erat. Vivamus suscipit dapibus orci quis sollicitudin.

Maecenas leo elit, lobortis eget malesuada vitae, rhoncus id arcu. Nunc sit amet mauris eget sapien rhoncus dignissim sed ac risus. Maecenas nec diam non odio euismod ultrices. Sed tempus lacus nisi, sed dapibus metus ornare vel. Curabitur semper eros nec massa dignissim gravida. Morbi neque leo, tincidunt id ipsum eget, condimentum congue libero. Phasellus feugiat urna sit amet sollicitudin imperdiet. Pellentesque eu ultrices enim. Vivamus consequat sem massa, sed feugiat neque cursus a. Mauris lacinia augue eros, eu cursus nisi imperdiet ut. Maecenas luctus turpis magna. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

Aenean a ornare turpis. Nunc lacinia vulputate neque, nec volutpat lorem rutrum at. Mauris nec laoreet nisi, vel porta odio. Curabitur dictum lacus non sapien interdum, quis maximus sapien tincidunt. Proin sit amet sapien metus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam at laoreet tellus. Praesent ac fermentum tellus, in tincidunt quam. Etiam eu suscipit est. Mauris ornare ipsum sit amet tellus luctus efficitur. Sed tincidunt odio cursus nunc ultricies, non mattis risus semper.

Aenean ornare neque enim, vitae rhoncus urna maximus eu. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer a ipsum in arcu vestibulum egestas. Suspendisse consectetur mattis massa, nec tincidunt metus convallis sed. Quisque interdum dui eget aliquet hendrerit. Curabitur ac odio semper risus rutrum ullamcorper. Sed vel placerat quam. Sed ipsum mi, facilisis et quam ac, sagittis viverra tortor. Cras vitae ultricies mi. Mauris viverra at risus eget tristique.

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin iaculis vestibulum neque semper ultricies. Curabitur leo eros, placerat ut felis in, tincidunt auctor turpis. Fusce porta magna nec tempor iaculis. Ut est lacus, sodales a laoreet at, pharetra in ligula. Sed in justo nulla. Nunc dictum elit a dui ultricies congue. Praesent sed volutpat magna, id fermentum eros. Quisque hendrerit magna quam, vitae dictum orci blandit ac. Maecenas pellentesque mollis sem, eu vehicula nisl placerat et. Nullam sodales nec tortor quis lacinia. Nam egestas mi at cursus maximus.

Praesent interdum sed nisi et egestas. Pellentesque sed massa ex. Mauris et lacus eu odio tristique sagittis. Nullam et orci metus. Nulla ac aliquam nulla, sed semper leo. Aliquam aliquam metus turpis, in varius metus tempor id. Cras pulvinar tellus ac mi sodales, vel faucibus nisi luctus. Aliquam erat volutpat. Ut vitae volutpat nisi, nec vulputate sapien.

Pellentesque in mauris a quam aliquam facilisis at vitae nunc. Curabitur consectetur sodales eros, ac euismod nibh pulvinar nec. Sed ullamcorper ipsum id quam cursus, nec pharetra elit imperdiet. Etiam eget ante in diam condimentum lacinia ac sit amet magna. Duis vel ullamcorper augue. Morbi finibus pulvinar purus eget tincidunt. Nunc consectetur elit nec fringilla mattis. Nam euismod et urna non pretium. Integer ullamcorper erat non tellus mollis tincidunt.
      </p>
    </div>
  )
}

export default MainContent